/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  formIntro?: string;
  serviceOptions?: Array<string>;
  phoneNote?: string;
  successHeading?: string;
  successBody?: string;
  successButtonLabel?: string;
  contactFields?: Array<
    {
      _key: string;
    } & FieldRow
  >;
  mapImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectPage = {
  _id: string;
  _type: "projectPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backLabel?: string;
  recordLine?: string;
  fieldLabels?: {
    client?: string;
    scope?: string;
    location?: string;
    status?: string;
  };
  prevLabel?: string;
  nextLabel?: string;
  commissionEyebrow?: string;
  defaultCommissionBody?: string;
};

export type DesignsPage = {
  _id: string;
  _type: "designsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  intro?: string;
  allFilterLabel?: string;
  defaultView?: "plates" | "index";
  seo?: Seo;
};

export type ConstructionPage = {
  _id: string;
  _type: "constructionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  intro?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  stagesBlock?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & NumberedItem
    >;
  };
  comparison?: {
    eyebrow?: string;
    title?: string;
    leftLabel?: string;
    rightLabel?: string;
    rows?: Array<
      {
        _key: string;
      } & ComparisonRow
    >;
  };
  capability?: {
    eyebrow?: string;
    title?: string;
    note?: string;
    items?: Array<
      {
        _key: string;
      } & NumberedItem
    >;
  };
  seo?: Seo;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  intro?: string;
  services?: Array<
    {
      _key: string;
    } & ServiceBlock
  >;
  constructionBand?: {
    eyebrow?: string;
    title?: string;
    body?: string;
    cta?: Cta;
  };
  sectorsBlock?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & NumberedItem
    >;
  };
  seo?: Seo;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    body?: string;
    ctas?: Array<
      {
        _key: string;
      } & Cta
    >;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  about?: {
    eyebrow?: string;
    statement?: string;
    body?: string;
    cta?: Cta;
    recordLabel?: string;
    stats?: Array<
      {
        _key: string;
      } & StatItem
    >;
  };
  disciplines?: {
    eyebrow?: string;
    title?: string;
    intro?: string;
    items?: Array<
      {
        _key: string;
      } & NumberedItem
    >;
    cta?: Cta;
    secondaryLink?: Cta;
  };
  works?: {
    eyebrow?: string;
    title?: string;
    linkLabel?: string;
    featuredProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  };
  leadership?: {
    eyebrow?: string;
    name?: string;
    roleLine?: string;
    bio?: string;
    portrait?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    credentials?: Array<
      {
        _key: string;
      } & FieldRow
    >;
  };
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  legalName?: string;
  tagline?: string;
  railLabel?: string;
  phones?: Array<string>;
  addressLines?: Array<string>;
  digitalAddress?: string;
  registrationLine?: string;
  credentialStrip?: Array<string>;
  nav?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  footerStatement?: string;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  officeColumnTitle?: string;
  ctaBand?: CtaBand;
  defaultSeo?: Seo;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & LinkItem
  >;
};

export type CtaBand = {
  _type: "ctaBand";
  heading?: string;
  body?: string;
  button?: Cta;
};

export type SectorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sector";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  scopeOfWorks?: string;
  location?: string;
  sector?: SectorReference;
  status?: "Completed" | "Ongoing" | "On hold";
  year?: number;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  gallery?: Array<
    {
      _key: string;
    } & Figure
  >;
  note?: string;
  commissionBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Sector = {
  _id: string;
  _type: "sector";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
};

export type ServiceBlock = {
  _type: "serviceBlock";
  title?: string;
  tag?: string;
  description?: string;
  items?: Array<string>;
};

export type ComparisonRow = {
  _type: "comparisonRow";
  conventional?: string;
  bejewelled?: string;
};

export type FieldRow = {
  _type: "fieldRow";
  label?: string;
  value?: string;
};

export type StatItem = {
  _type: "statItem";
  value?: string;
  label?: string;
};

export type NumberedItem = {
  _type: "numberedItem";
  title?: string;
  body?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & LinkItem
  >;
};

export type LinkItem = {
  _type: "linkItem";
  label?: string;
  href?: string;
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ContactPage
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectPage
  | DesignsPage
  | ConstructionPage
  | ServicesPage
  | Cta
  | ProjectReference
  | HomePage
  | SiteSettings
  | CtaBand
  | SectorReference
  | Project
  | Slug
  | Sector
  | ServiceBlock
  | ComparisonRow
  | FieldRow
  | StatItem
  | NumberedItem
  | FooterColumn
  | LinkItem
  | Figure
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    brandName,    legalName,    tagline,    railLabel,    phones,    addressLines,    digitalAddress,    registrationLine,    credentialStrip,    nav[]{label, href},    footerStatement,    footerColumns[]{title, items[]{label, href}},    officeColumnTitle,    ctaBand{heading, body, button{label, href}},    defaultSeo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}},    ogImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},    socialLinks[]{label, href}  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      brandName: null;
      legalName: null;
      tagline: null;
      railLabel: null;
      phones: null;
      addressLines: null;
      digitalAddress: null;
      registrationLine: null;
      credentialStrip: null;
      nav: null;
      footerStatement: null;
      footerColumns: null;
      officeColumnTitle: null;
      ctaBand: null;
      defaultSeo: null;
      ogImage: null;
      socialLinks: null;
    }
  | {
      brandName: string | null;
      legalName: string | null;
      tagline: string | null;
      railLabel: string | null;
      phones: Array<string> | null;
      addressLines: Array<string> | null;
      digitalAddress: string | null;
      registrationLine: string | null;
      credentialStrip: Array<string> | null;
      nav: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      footerStatement: string | null;
      footerColumns: Array<{
        title: string | null;
        items: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      }> | null;
      officeColumnTitle: string | null;
      ctaBand: {
        heading: string | null;
        body: string | null;
        button: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      defaultSeo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      ogImage: {
        alt: null;
        caption: null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      socialLinks: Array<{
        label: string | null;
        href: string | null;
      }> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{eyebrow, title, body, ctas[]{label, href}, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}},    about{      eyebrow,      statement,      body,      cta{label, href},      recordLabel,      stats[]{value, label}    },    disciplines{      eyebrow,      title,      intro,      items[]{title, body},      cta{label, href},      secondaryLink{label, href}    },    works{      eyebrow,      title,      linkLabel,      "featured": select(        count(featuredProjects) > 0 => featuredProjects[]->{  _id,  "slug": slug.current,  "client": coalesce(client, title),  scopeOfWorks,  location,  status,  "sector": sector->title,  mainImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}},        *[_type == "project" && defined(slug.current)] | order(orderRank asc)[0...3]{  _id,  "slug": slug.current,  "client": coalesce(client, title),  scopeOfWorks,  location,  status,  "sector": sector->title,  mainImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}      )    },    leadership{      eyebrow,      name,      roleLine,      bio,      portrait {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},      credentials[]{label, value}    },    seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}},    "projectOrder": *[_type == "project" && defined(slug.current)] | order(orderRank asc)._id  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      about: null;
      disciplines: null;
      works: null;
      leadership: null;
      seo: null;
      projectOrder: Array<string>;
    }
  | {
      hero: null;
      about: null;
      disciplines: null;
      works: null;
      leadership: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      projectOrder: Array<string>;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        body: string | null;
        ctas: Array<{
          label: string | null;
          href: string | null;
        }> | null;
        image: {
          alt: string | null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      about: {
        eyebrow: string | null;
        statement: string | null;
        body: string | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
        recordLabel: string | null;
        stats: Array<{
          value: string | null;
          label: string | null;
        }> | null;
      } | null;
      disciplines: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
        items: Array<{
          title: string | null;
          body: string | null;
        }> | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
        secondaryLink: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      works: {
        eyebrow: string | null;
        title: string | null;
        linkLabel: string | null;
        featured: Array<{
          _id: string;
          slug: string | null;
          client: string | null;
          scopeOfWorks: string | null;
          location: string | null;
          status: "Completed" | "On hold" | "Ongoing" | null;
          sector: string | null;
          mainImage: {
            alt: string | null;
            caption: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        }> | null;
      } | null;
      leadership: {
        eyebrow: string | null;
        name: string | null;
        roleLine: string | null;
        bio: string | null;
        portrait: {
          alt: string | null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        credentials: Array<{
          label: string | null;
          value: string | null;
        }> | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      projectOrder: Array<string>;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_id == "servicesPage"][0]{    eyebrow,    title,    intro,    services[]{title, tag, description, items},    constructionBand{eyebrow, title, body, cta{label, href}},    sectorsBlock{eyebrow, title, items[]{title, body}},    seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}  }
export type SERVICES_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      title: null;
      intro: null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: string | null;
      intro: null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: null;
      intro: null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: null;
      title: string | null;
      intro: null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: string | null;
      services: null;
      constructionBand: null;
      sectorsBlock: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: string | null;
      services: Array<{
        title: string | null;
        tag: string | null;
        description: string | null;
        items: Array<string> | null;
      }> | null;
      constructionBand: {
        eyebrow: string | null;
        title: string | null;
        body: string | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      sectorsBlock: {
        eyebrow: string | null;
        title: string | null;
        items: Array<{
          title: string | null;
          body: string | null;
        }> | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    eyebrow,    title,    formIntro,    serviceOptions,    phoneNote,    successHeading,    successBody,    successButtonLabel,    contactFields[]{label, value},    mapImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},    seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      title: null;
      formIntro: null;
      serviceOptions: null;
      phoneNote: null;
      successHeading: null;
      successBody: null;
      successButtonLabel: null;
      contactFields: null;
      mapImage: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: string | null;
      formIntro: null;
      serviceOptions: null;
      phoneNote: null;
      successHeading: null;
      successBody: null;
      successButtonLabel: null;
      contactFields: null;
      mapImage: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: null;
      formIntro: null;
      serviceOptions: null;
      phoneNote: null;
      successHeading: null;
      successBody: null;
      successButtonLabel: null;
      contactFields: null;
      mapImage: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: null;
      title: string | null;
      formIntro: null;
      serviceOptions: null;
      phoneNote: null;
      successHeading: null;
      successBody: null;
      successButtonLabel: null;
      contactFields: null;
      mapImage: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      formIntro: null;
      serviceOptions: null;
      phoneNote: null;
      successHeading: null;
      successBody: null;
      successButtonLabel: null;
      contactFields: null;
      mapImage: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      formIntro: string | null;
      serviceOptions: Array<string> | null;
      phoneNote: string | null;
      successHeading: string | null;
      successBody: string | null;
      successButtonLabel: string | null;
      contactFields: Array<{
        label: string | null;
        value: string | null;
      }> | null;
      mapImage: {
        alt: string | null;
        caption: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: DESIGNS_PAGE_QUERY
// Query: {    "page": *[_id == "designsPage"][0]{      eyebrow,      title,      intro,      allFilterLabel,      defaultView,      seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}    },    "sectors": *[_type == "sector"] | order(orderRank asc){      title,      "slug": slug.current    },    "projects": *[_type == "project" && defined(slug.current)] | order(orderRank asc){      ...{  _id,  "slug": slug.current,  "client": coalesce(client, title),  scopeOfWorks,  location,  status,  "sector": sector->title,  mainImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}},      "sectorSlug": sector->slug.current    }  }
export type DESIGNS_PAGE_QUERY_RESULT = {
  page:
    | {
        eyebrow: null;
        title: null;
        intro: null;
        allFilterLabel: null;
        defaultView: null;
        seo: null;
      }
    | {
        eyebrow: null;
        title: string | null;
        intro: null;
        allFilterLabel: null;
        defaultView: null;
        seo: null;
      }
    | {
        eyebrow: null;
        title: null;
        intro: null;
        allFilterLabel: null;
        defaultView: null;
        seo: {
          title: string | null;
          description: string | null;
          noIndex: boolean | null;
          image: {
            alt: null;
            caption: null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        eyebrow: null;
        title: string | null;
        intro: null;
        allFilterLabel: null;
        defaultView: null;
        seo: {
          title: string | null;
          description: string | null;
          noIndex: boolean | null;
          image: {
            alt: null;
            caption: null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        eyebrow: string | null;
        title: string | null;
        intro: null;
        allFilterLabel: null;
        defaultView: null;
        seo: {
          title: string | null;
          description: string | null;
          noIndex: boolean | null;
          image: {
            alt: null;
            caption: null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
        allFilterLabel: null;
        defaultView: null;
        seo: {
          title: string | null;
          description: string | null;
          noIndex: boolean | null;
          image: {
            alt: null;
            caption: null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
        allFilterLabel: string | null;
        defaultView: "index" | "plates" | null;
        seo: {
          title: string | null;
          description: string | null;
          noIndex: boolean | null;
          image: {
            alt: null;
            caption: null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                  aspectRatio: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | null;
  sectors: Array<{
    title: string | null;
    slug: string | null;
  }>;
  projects: Array<{
    _id: string;
    slug: string | null;
    client: string | null;
    scopeOfWorks: string | null;
    location: string | null;
    status: "Completed" | "On hold" | "Ongoing" | null;
    sector: string | null;
    mainImage: {
      alt: string | null;
      caption: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    sectorSlug: string | null;
  }>;
};

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: {    "project": *[_type == "project" && slug.current == $slug][0]{      _id,      "slug": slug.current,      "client": coalesce(client, title),      title,      scopeOfWorks,      location,      status,      year,      "sector": sector->title,      note,      commissionBody,      mainImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},      gallery[] {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},      seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}    },    "template": *[_id == "projectPage"][0]{      backLabel,      recordLine,      fieldLabels{client, scope, location, status},      prevLabel,      nextLabel,      commissionEyebrow,      defaultCommissionBody    },    "order": *[_type == "project" && defined(slug.current)] | order(orderRank asc){      _id,      "slug": slug.current,      "client": coalesce(client, title)    }  }
export type PROJECT_QUERY_RESULT = {
  project: {
    _id: string;
    slug: string | null;
    client: string | null;
    title: string | null;
    scopeOfWorks: string | null;
    location: string | null;
    status: "Completed" | "On hold" | "Ongoing" | null;
    year: number | null;
    sector: string | null;
    note: string | null;
    commissionBody: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    mainImage: {
      alt: string | null;
      caption: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    gallery: Array<{
      alt: string | null;
      caption: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    }> | null;
    seo: {
      title: string | null;
      description: string | null;
      noIndex: boolean | null;
      image: {
        alt: null;
        caption: null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  template:
    | {
        backLabel: null;
        recordLine: null;
        fieldLabels: null;
        prevLabel: null;
        nextLabel: null;
        commissionEyebrow: null;
        defaultCommissionBody: null;
      }
    | {
        backLabel: string | null;
        recordLine: string | null;
        fieldLabels: {
          client: string | null;
          scope: string | null;
          location: string | null;
          status: string | null;
        } | null;
        prevLabel: string | null;
        nextLabel: string | null;
        commissionEyebrow: string | null;
        defaultCommissionBody: string | null;
      }
    | null;
  order: Array<{
    _id: string;
    slug: string | null;
    client: string | null;
  }>;
};

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/sanity/queries.ts
// Variable: CONSTRUCTION_PAGE_QUERY
// Query: *[_id == "constructionPage"][0]{    eyebrow,    title,    intro,    heroImage {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}},    stagesBlock{eyebrow, title, items[]{title, body}},    comparison{      eyebrow,      title,      leftLabel,      rightLabel,      rows[]{conventional, bejewelled}    },    capability{eyebrow, title, note, items[]{title, body}},    seo{title, description, noIndex, image {  alt,  caption,  hotspot,  crop,  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}}}  }
export type CONSTRUCTION_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      title: null;
      intro: null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: string | null;
      intro: null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: null;
    }
  | {
      eyebrow: null;
      title: null;
      intro: null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: null;
      title: string | null;
      intro: null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: string | null;
      heroImage: null;
      stagesBlock: null;
      comparison: null;
      capability: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      intro: string | null;
      heroImage: {
        alt: string | null;
        caption: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      stagesBlock: {
        eyebrow: string | null;
        title: string | null;
        items: Array<{
          title: string | null;
          body: string | null;
        }> | null;
      } | null;
      comparison: {
        eyebrow: string | null;
        title: string | null;
        leftLabel: string | null;
        rightLabel: string | null;
        rows: Array<{
          conventional: string | null;
          bejewelled: string | null;
        }> | null;
      } | null;
      capability: {
        eyebrow: string | null;
        title: string | null;
        note: string | null;
        items: Array<{
          title: string | null;
          body: string | null;
        }> | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          alt: null;
          caption: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    brandName,\n    legalName,\n    tagline,\n    railLabel,\n    phones,\n    addressLines,\n    digitalAddress,\n    registrationLine,\n    credentialStrip,\n    nav[]{label, href},\n    footerStatement,\n    footerColumns[]{title, items[]{label, href}},\n    officeColumnTitle,\n    ctaBand{heading, body, button{label, href}},\n    defaultSeo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}},\n    ogImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n    socialLinks[]{label, href}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    hero{eyebrow, title, body, ctas[]{label, href}, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}},\n    about{\n      eyebrow,\n      statement,\n      body,\n      cta{label, href},\n      recordLabel,\n      stats[]{value, label}\n    },\n    disciplines{\n      eyebrow,\n      title,\n      intro,\n      items[]{title, body},\n      cta{label, href},\n      secondaryLink{label, href}\n    },\n    works{\n      eyebrow,\n      title,\n      linkLabel,\n      "featured": select(\n        count(featuredProjects) > 0 => featuredProjects[]->{\n  _id,\n  "slug": slug.current,\n  "client": coalesce(client, title),\n  scopeOfWorks,\n  location,\n  status,\n  "sector": sector->title,\n  mainImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}\n},\n        *[_type == "project" && defined(slug.current)] | order(orderRank asc)[0...3]{\n  _id,\n  "slug": slug.current,\n  "client": coalesce(client, title),\n  scopeOfWorks,\n  location,\n  status,\n  "sector": sector->title,\n  mainImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}\n}\n      )\n    },\n    leadership{\n      eyebrow,\n      name,\n      roleLine,\n      bio,\n      portrait {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n      credentials[]{label, value}\n    },\n    seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}},\n    "projectOrder": *[_type == "project" && defined(slug.current)] | order(orderRank asc)._id\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "servicesPage"][0]{\n    eyebrow,\n    title,\n    intro,\n    services[]{title, tag, description, items},\n    constructionBand{eyebrow, title, body, cta{label, href}},\n    sectorsBlock{eyebrow, title, items[]{title, body}},\n    seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}}\n  }\n': SERVICES_PAGE_QUERY_RESULT;
    '\n  *[_id == "contactPage"][0]{\n    eyebrow,\n    title,\n    formIntro,\n    serviceOptions,\n    phoneNote,\n    successHeading,\n    successBody,\n    successButtonLabel,\n    contactFields[]{label, value},\n    mapImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n    seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}}\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  {\n    "page": *[_id == "designsPage"][0]{\n      eyebrow,\n      title,\n      intro,\n      allFilterLabel,\n      defaultView,\n      seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}}\n    },\n    "sectors": *[_type == "sector"] | order(orderRank asc){\n      title,\n      "slug": slug.current\n    },\n    "projects": *[_type == "project" && defined(slug.current)] | order(orderRank asc){\n      ...{\n  _id,\n  "slug": slug.current,\n  "client": coalesce(client, title),\n  scopeOfWorks,\n  location,\n  status,\n  "sector": sector->title,\n  mainImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}\n},\n      "sectorSlug": sector->slug.current\n    }\n  }\n': DESIGNS_PAGE_QUERY_RESULT;
    '\n  {\n    "project": *[_type == "project" && slug.current == $slug][0]{\n      _id,\n      "slug": slug.current,\n      "client": coalesce(client, title),\n      title,\n      scopeOfWorks,\n      location,\n      status,\n      year,\n      "sector": sector->title,\n      note,\n      commissionBody,\n      mainImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n      gallery[] {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n      seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}}\n    },\n    "template": *[_id == "projectPage"][0]{\n      backLabel,\n      recordLine,\n      fieldLabels{client, scope, location, status},\n      prevLabel,\n      nextLabel,\n      commissionEyebrow,\n      defaultCommissionBody\n    },\n    "order": *[_type == "project" && defined(slug.current)] | order(orderRank asc){\n      _id,\n      "slug": slug.current,\n      "client": coalesce(client, title)\n    }\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_id == "constructionPage"][0]{\n    eyebrow,\n    title,\n    intro,\n    heroImage {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n},\n    stagesBlock{eyebrow, title, items[]{title, body}},\n    comparison{\n      eyebrow,\n      title,\n      leftLabel,\n      rightLabel,\n      rows[]{conventional, bejewelled}\n    },\n    capability{eyebrow, title, note, items[]{title, body}},\n    seo{title, description, noIndex, image {\n  alt,\n  caption,\n  hotspot,\n  crop,\n  asset->{_id, metadata{lqip, dimensions{width, height, aspectRatio}}}\n}}\n  }\n': CONSTRUCTION_PAGE_QUERY_RESULT;
  }
}
